version: "3"
services:
  jd_zhangmi:
    image: python:3.12.4
    container_name: jd_zhangmi
    restart: unless-stopped
    ports:
      - 自定义端口:12345
    working_dir: /usr/src/app
    volumes:
      - 自定义路径:/usr/src/app
    command: >
      sh -c "apt-get update \
             && apt-get install -y --no-install-recommends libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2 libatspi2.0-0 libxshmfence1 \
             && python -m pip install --upgrade pip \
             && pip install pyppeteer Pillow aiohttp opencv-python-headless ddddocr quart \
             && cp -r /home/账密登录/app/api.py /usr/src/app \
             && cp -r /home/账密登录/app/login.py /usr/src/app \
             && python api.py"
networks:
  bridge:
    external: true


上面
/home/账密登录/app/login.py
/home/账密登录/app/api.py
改成自己本机放两文件的路径，另外
启动容器后
需要等亿段段段段段时间，等初次启动拉取依赖
apt-get update和拉依赖很慢，自备代理、改容器内镜像源或者熬老头等加载完代码